### PR TITLE
gets the script running again. closes #2

### LINKED ISSUE #2: It's set to work with deprecated v1beta1
Only raises googleapiclient.errors.ResumableUploadError: <HttpError 400 "Version v1beta1 of this API is no longer available. Please try again using JSON API v1. To request temporary reinstatement for your project, please visit https://docs.google.com/forms/d/1isIxBZg3rsQbDN_TOalZaz1WT_ebJchsrlv-Qr_r9mY/viewform?entry.244568692=996887061330&entry.176324201=v1beta1&entry.1071661541-Qr_r9mY/prefill">

### PR DESCRIPTION
**Pull request by caioiglesias**
Fixes #2

### CODE REVIEW

**Comment by caioiglesias** [comment]
Can't someone just merge this?

**Comment by tmatsuo** [comment]
Hi @caioiglesias 

Sorry for the late reply and thanks for the patch.
In order for use to merge your change, can you sign one of our CLA described in:
https://github.com/GoogleCloudPlatform/storage-file-transfer-json-python/blob/master/CONTRIB.md
?

Thanks,

**Comment by caioiglesias** [comment]
Done!

**Comment by tmatsuo** [comment]
thx!

**Pull request merged**
